name: Deploy Odoo Modules

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up SSH
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      # Copy updated modules to VPS
      - name: Deploy modules to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ \
            devbf@<VPS_IP>:/home/devbf/own/
      
      # Restart Odoo service
      - name: Restart Odoo service
        run: |
          ssh -o StrictHostKeyChecking=no devbf@<VPS_IP> \
            "sudo service odoo13 restart"
